replicaCount: 1
image:
  repository: ghcr.io/fitnest-backend/notifications-service
  tag: "development-d7b8e36"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
istio:
  enabled: true
  host: "notifications-service"
  mtls:
    mode: STRICT
  authorization:
    internalCallers:
      - "cluster.local/ns/fitnest-dev/sa/user-service"
      - "cluster.local/ns/fitnest-dev/sa/identity-service"
      - "cluster.local/ns/fitnest-dev/sa/order-service"
      - "cluster.local/ns/fitnest-dev/sa/api-gateway"
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"
env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: "jdbc:postgresql://postgresql-notifications:5432/fitnest_notifications"
  SPRING_DATASOURCE_USERNAME: "fitnest_notifications"
  SPRING_DATASOURCE_PASSWORD: "notifications_password_123"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_MAIL_HOST: "smtp.gmail.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_USERNAME: "fitnestazerbaijan@gmail.com"
  SPRING_MAIL_PASSWORD: "lktq jnyn txhg sumu"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_FROM: "fitnestazerbaijan@gmail.com"
  SPRING_DATA_REDIS_HOST: "redis"
  SPRING_DATA_REDIS_PORT: "6379"
  SPRING_DATA_REDIS_PASSWORD: ""
  SMS_LOGIN: "YOUR_LOGIN"
  SMS_PASSWORD: "YOUR_PASSWORD"
  SMS_SENDER: "YOUR_SENDER"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "az.fitnest.*,az.fitnest.identity.model.event"
  JWT_SECRET: "your-jwt-secret-change-in-production"
  JWT_ISSUER: "fitnest"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"
  STORAGE_SERVICE_URL: "http://storage-service:8080"
  JAVA_TOOL_OPTIONS: "-Xms256m -Xmx400m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:MaxMetaspaceSize=128m -Xss512k -XX:+ExitOnOutOfMemoryError"
  APP_FIREBASE_ENABLED: "true"
  APP_FIREBASE_CONFIG_PATH: "/app/firebase/serviceAccountKey.json"
resources:
  requests:
    cpu: 200m
    memory: 450Mi
  limits:
    cpu: 500m
    memory: 800Mi
firebase:
  secretName: firebase-sa
  mountPath: /app/firebase
