firebase:
  mountPath: /app/firebase
  secretName: firebase-sa
hpa:
  cpuUtilization: '90'
  enabled: false
  maxReplicas: '3'
  memoryUtilization: 450Mi
  minReplicas: '1'
image:
  imagePullSecrets:
    - name: ghcr-secret
  pullPolicy: IfNotPresent
  repository: ghcr.io/fitnest-code/notifications-backend
  tag: production-b16ac67
networkPolicy:
  allowedServices:
    - user-backend
    - identity-backend
    - order-backend
  enabled: true
replicaCount: 1
resources:
  limits:
    cpu: 1000m
    memory: 1312Mi
  requests:
    cpu: 23m
    memory: 853Mi
service:
  grpcPort: 9090
  port: 8080
  type: ClusterIP
vaultEnv: production
