vaultEnv: development
# values.yaml for notifications-backend

replicaCount: 1
image:
  repository: ghcr.io/fitnest-code/notifications-backend
  tag: "development-f462c60"
  pullPolicy: IfNotPresent
  imagePullSecrets:
    - name: ghcr-secret
service:
  type: ClusterIP
  port: 8080
  grpcPort: 9090
networkPolicy:
  enabled: true
  allowedServices:
    - user-backend
    - identity-backend
    - order-backend
    # gateway-backend is already hardcoded in the policy template
hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"
env:
  SPRING_PROFILES_ACTIVE: "dev"
  SPRINGDOC_SERVER_URL: "https://dev-api.fitnest.az"
  SPRING_DATASOURCE_URL: jdbc:postgresql://10.0.0.4:5432/fitnest_notifications?sslmode=disable
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
  SPRING_MAIL_HOST: "smtp.zoho.com"
  SPRING_MAIL_PORT: "587"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_AUTH: "true"
  SPRING_MAIL_PROPERTIES_MAIL_SMTP_STARTTLS_ENABLE: "true"
  SPRING_MAIL_FROM: "notifications@fitnest.az" # This can be overridden or mapped from secret if needed
  SPRING_DATA_REDIS_HOST: "10.0.0.4"
  SPRING_DATA_REDIS_PORT: "6380"
  SPRING_DATA_REDIS_TIMEOUT: "2000ms"
  KAFKA_BOOTSTRAP_SERVERS: "10.0.0.4:9092"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_TRUSTED_PACKAGES: "az.fitnest.*,az.fitnest.identity.model.event"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_USE_TYPE_HEADERS: "false"
  SPRING_KAFKA_CONSUMER_PROPERTIES_SPRING_JSON_VALUE_DEFAULT_TYPE: "az.fitnest.notifications.messaging.NotificationEvent"
  JWT_ISSUER: "fitnest"
  IDENTITY_BACKEND_URL: "http://identity-backend:8080"
  USER_BACKEND_URL: "http://user-backend:8080"
  STORAGE_BACKEND_URL: "http://storage-backend:8080"
  USE_GRPC_STORAGE: "false"
  STORAGE_GRPC_ADDRESS: "dns:///storage-backend.fitnest-development.svc.cluster.local:9090"
  JAVA_TOOL_OPTIONS: >
    -Xms256m -Xmx512m -XX:+UseG1GC -XX:MaxGCPauseMillis=200 -XX:+ParallelRefProcEnabled -XX:MaxMetaspaceSize=256m -XX:+AlwaysPreTouch -Xss512k -XX:+ExitOnOutOfMemoryError

  APP_FIREBASE_ENABLED: "true"
  APP_FIREBASE_CONFIG_PATH: "/app/firebase/serviceAccountKey.json"
resources:
  requests:
    cpu: 23m
    memory: 853Mi
  limits:
    cpu: 1000m
    memory: 1312Mi
firebase:
  secretName: firebase-sa
  mountPath: /app/firebase
