apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "notifications-service.fullname" .}}
  labels:
    {{- include "notifications-service.labels" . | nindent 4}}
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      {{- include "notifications-service.selectorLabels" . | nindent 6}}
  template:
    metadata:
      labels:
        {{- include "notifications-service.selectorLabels" . | nindent 8}}
      annotations:
        {{- if .Values.istio.enabled}}
        sidecar.istio.io/inject: "true"
        {{- end}}
    spec:
      serviceAccountName: {{ include "notifications-service.fullname" .}}
      {{- with .Values.image.imagePullSecrets}}
      imagePullSecrets:
        {{- toYaml . | nindent 8}}
      {{- end}}
      containers:
        - name: {{ .Chart.Name}}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy}}
          ports:
            - name: http
              containerPort: {{ .Values.service.port}}
              protocol: TCP
            - name: grpc
              containerPort: {{ .Values.service.grpcPort}}
              protocol: TCP
          {{- if .Values.env}}
          env:
          {{- range $key, $value := .Values.env}}
          - name: {{ $key}}
            value: {{ $value | quote}}
          {{- end}}
          {{- end}}
          volumeMounts:
            - name: firebase-sa-volume
              mountPath: {{ .Values.firebase.mountPath}}
              readOnly: true
          {{- if .Values.livenessProbe}}
          livenessProbe:
{{ toYaml .Values.livenessProbe | nindent 12}}
          {{- end}}
          {{- if .Values.readinessProbe}}
          readinessProbe:
{{ toYaml .Values.readinessProbe | nindent 12}}
          {{- end}}
          resources:
{{ toYaml .Values.resources | nindent 12}}
      volumes:
        - name: firebase-sa-volume
          secret:
            secretName: {{ .Values.firebase.secretName}}
